### ISSUE TITLE
BurpSuite version don't recognized

### ISSUE THREAD

**Issue by sguarin** [iesplin/ansible-role-burpsuite#1]
First trying to test your ansible 4 kali and I got:

```
...
TASK [ansible-role-burpsuite : Get version number] *****************************************************************************************************************************************************************************************
task path: /home/xxx/.ansible/roles/ansible-role-burpsuite/tasks/main.yml:55
fatal: [192.168.1.165]: FAILED! => {
    "msg": "JMESPathError in json_query filter plugin:\nIn function sort(), invalid type for value: 2021.8.4, expected one of: ['array-string', 'array-number'], received: \"AnsibleUnsafeText\""
}
...
```

**Comment by sguarin** [comment]
Found this [workaround](https://github.com/ansible/ansible/issues/27299#issuecomment-486672245)
from_json | to_json | jsonq_query(query) seems to fix the jmespath ansible issue

So something like seems to fix my problem
```
    - name: Get version number
      ansible.builtin.set_fact:
        burpsuite_version: "{{ burp_release_data | to_json | from_json | json_query(version_query) }}"
      vars:
        version_query: "ResultSet.Results[?releaseChannels[0]=='{{_burpsuite_release_channel_enum[burpsuite_release_channel]}}' && builds[?ProductId == '{{ burpsuite_product_type }}' && ProductPlatform=='Linux']].version | sort(@)[-1]"
```
